name: DockerImages

on:
  schedule:
    - cron: '0 10 * * 1' # every monday at 10am
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  check:
    name: Check Updates
    runs-on: ubuntu-latest
    outputs:
      gitbucket: ${{ steps.gitbucket.outputs.update }}
      registry: ${{ steps.registry.outputs.update }}
      runner-foxy: ${{ steps.runner-foxy.outputs.update }}
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Check Gitbucket Version
        id: gitbucket
        run: |
          update=$(python3 scripts/check_updates.py gitbucket/gitbucket jqjiang/gitbucket)
          echo "::set-output name=update::$update"
      - name: Check Registry Version
        id: registry
        run: |
          update=$(python3 scripts/check_updates.py distribution/distribution jqjiang/registry)
          echo "::set-output name=update::$update"
      - name: Check Foxy Runner Version
        id: runner-foxy
        run: |
          update=$(python3 scripts/check_updates.py actions/runner jqjiang/runner-ros-foxy)
          echo "::set-output name=update::$update"
  
  build:
    name: Build Images
    needs: check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build Gitbucket Image
        if: ${{ needs.check.outputs.gitbucket != 'false' }}
        uses: docker/build-push-action@v2
        with:
          push: true
          file: docker/gitbucket.Dockerfile
          tags: jqjiang/gitbucket:latest,jqjiang/gitbucket:${{ needs.check.outputs.gitbucket }}
          context: docker
          build-args: |
            VERSION=${{ needs.check.outputs.gitbucket }}
      - name: Build Registry Image
        if: ${{ needs.check.outputs.registry != 'false' }}
        uses: docker/build-push-action@v2
        with:
          push: true
          file: docker/registry.Dockerfile
          tags: jqjiang/registry:latest,jqjiang/registry:${{ needs.check.outputs.registry }}
          context: docker
          build-args: |
            VERSION=${{ needs.check.outputs.registry }}

      - name: Build ROS Runner Image
        if: ${{ needs.check.outputs.runner-foxy != 'false' }}
        uses: docker/build-push-action@v2
        with:
          push: true
          file: docker/runner-ros-foxy.Dockerfile
          tags: jqjiang/runner-ros-foxy:latest,jqjiang/runner-ros-foxy:${{ needs.check.outputs.runner-foxy }}
          context: docker
          build-args: |
            VERSION=${{ needs.check.outputs.runner-foxy }}
